require "Items/ProceduralDistributions"

-- FunctionalCarLift.CarLiftMag
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.8);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.8);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["GasStorageMechanics"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["GasStorageMechanics"].items, 0.8);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1);
table.insert(ProceduralDistributions.list["LivingRoomSideTable"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["LivingRoomSideTable"].items, 0.1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.8);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicSpecial"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["MechanicSpecial"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "FunctionalCarLift.CarLiftMag");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);